version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpass
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://crmuser:crmpass@db:5432/crm
      JWT_SECRET: super-secret-change-me
      PORT: 4000
    depends_on:
      - db
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4000/api
    depends_on:
      - backend

volumes:
  dbdata:
